export const PRODUCTS = [
  {
    id: 1,
    title: 'Connection Man Teeshirt',
    img_path: 'connection/connection man tee',
    genre: 'Man',
    design: 'connection',
    type: 'teeshirts',
    price: 25,
  },
  {
    id: 2,
    title: 'Connection Woman Teeshirt',
    img_path: 'connection/connection woman tee',
    genre: 'Woman',
    design: 'connection',
    type: 'teeshirts',
    price: 25,
  },
  {
    id: 3,
    title: 'Connection Oversized Man Teeshirt',
    img_path: 'connection/connection oversized man tee',
    genre: 'Man',
    design: 'connection',
    type: 'teeshirts',
    price: 25,
  },
  {
    id: 4,
    title: 'Connection Oversized Woman Teeshirt',
    img_path: 'connection/connection oversized woman tee',
    genre: 'Woman',
    design: 'connection',
    type: 'teeshirts',
    price: 25,
  },

  {
    id: 5,
    title: 'Dont Panic Its Legal Man Teeshirt',
    img_path: 'don_t panic it_s legal/don_t panic it_s legal man tee',
    genre: 'Man',
    design: 'dont panic its legal',
    type: 'teeshirts',
    price: 25,
  },
  {
    id: 6,
    title: 'Dont Panic Its Legal Woman Teeshirt',
    img_path: 'don_t panic it_s legal/don_t panic it_s legal woman tee',
    genre: 'Woman',
    design: 'dont panic its legal',
    type: 'teeshirts',
    price: 25,
  },
  {
    id: 7,
    title: 'Dont Panic Its Legal Oversized Man Teeshirt',
    img_path: 'don_t panic it_s legal/don_t panic it_s legal oversized man tee',
    genre: 'Man',
    design: 'dont panic its legal',
    type: 'teeshirts',
    price: 25,
  },
  {
    id: 8,
    title: 'Dont Panic Its Legal Oversized Woman Teeshirt',
    img_path: 'don_t panic it_s legal/don_t panic it_s legal oversized woman tee',
    genre: 'Woman',
    design: 'dont panic its legal',
    type: 'teeshirts',
    price: 25,
  },

  {
    id: 9,
    title: 'Keep Calm and Love Music Man Teeshirt',
    img_path: 'keep calm and love music/keep calm and love music man tee',
    genre: 'Man',
    design: 'keep calm and love music',
    type: 'teeshirts',
    price: 25,
  },
  {
    id: 10,
    title: 'Keep Calm and Love Music Woman Teeshirt',
    img_path: 'keep calm and love music/keep calm and love music woman tee',
    genre: 'Woman',
    design: 'keep calm and love music',
    type: 'teeshirts',
    price: 25,
  },
  {
    id: 11,
    title: 'Keep Calm and Love Music Oversized Man Teeshirt',
    img_path: 'keep calm and love music/keep calm and love music oversized man tee',
    genre: 'Man',
    design: 'keep calm and love music',
    type: 'teeshirts',
    price: 25,
  },
  {
    id: 12,
    title: 'Keep Calm and Love Music Oversized Woman Teeshirt',
    img_path: 'keep calm and love music/keep calm and love music oversized woman tee',
    genre: 'Woman',
    design: 'keep calm and love music',
    type: 'teeshirts',
    price: 25,
  },
  {
    id: 13,
    title: 'Lets Vibe With Me Oversized Woman Teeshirt',
    img_path: 'let_s vibe with me/let_s vibe with me oversized woman tee',
    genre: 'Woman',
    design: 'let_s vibe with me',
    type: 'teeshirts',
    price: 25,
  },
  {
    id: 14,
    title: 'Lets Vibe With Me Woman Teeshirt',
    img_path: 'let_s vibe with me/let_s vibe with me woman tee',
    genre: 'Woman',
    design: 'let_s vibe with me',
    type: 'teeshirts',
    price: 25,
  },
  {
    id: 15,
    title: 'Mushroom Head Man Teeshirt',
    img_path: 'mushroom head/mushroom head man tee',
    genre: 'Man',
    design: 'mushroom head',
    type: 'teeshirts',
    price: 25,
  },
  {
    id: 16,
    title: 'Mushroom Head Woman Teeshirt',
    img_path: 'mushroom head/mushroom head woman tee',
    genre: 'Woman',
    design: 'mushroom head',
    type: 'teeshirts',
    price: 25,
  },
  {
    id: 17,
    title: 'Mushroom Head Oversized Man Teeshirt',
    img_path: 'mushroom head/mushroom head oversized man tee',
    genre: 'Man',
    design: 'mushroom head',
    type: 'teeshirts',
    price: 25,
  },
  {
    id: 18,
    title: 'Mushroom Head Oversized Woman Teeshirt',
    img_path: 'mushroom head/mushroom head oversized woman tee',
    genre: 'Woman',
    design: 'mushroom head',
    type: 'teeshirts',
    price: 25,
  },
  {
    id: 19,
    title: 'Music and Peace Man Teeshirt',
    img_path: 'music and peace/music and peace man tee',
    genre: 'Man',
    design: 'music and peace',
    type: 'teeshirts',
    price: 25,
  },
  {
    id: 20,
    title: 'Music and Peace Woman Teeshirt',
    img_path: 'music and peace/music and peace woman tee',
    genre: 'Woman',
    design: 'music and peace',
    type: 'teeshirts',
    price: 25,
  },
  {
    id: 21,
    title: 'Music and Peace Oversized Man Teeshirt',
    img_path: 'music and peace/music and peace oversized man tee',
    genre: 'Man',
    design: 'music and peace',
    type: 'teeshirts',
    price: 25,
  },
  {
    id: 22,
    title: 'Music and Peace Oversized Woman Teeshirt',
    img_path: 'music and peace/music and peace oversized woman tee',
    genre: 'Woman',
    design: 'music and peace',
    type: 'teeshirts',
    price: 25,
  },
  {
    id: 23,
    title: 'Perfectly Imperfect Man Teeshirt',
    img_path: 'perfectly imperfect/perfectly imperfect man tee',
    genre: 'Man',
    design: 'perfectly imperfect',
    type: 'teeshirts',
    price: 25,
  },
  {
    id: 24,
    title: 'Perfectly Imperfect Woman Teeshirt',
    img_path: 'perfectly imperfect/perfectly imperfect woman tee',
    genre: 'Woman',
    design: 'perfectly imperfect',
    type: 'teeshirts',
    price: 25,
  },
  {
    id: 25,
    title: 'Perfectly Imperfect Oversized Man Teeshirt',
    img_path: 'perfectly imperfect/perfectly imperfect oversized man tee',
    genre: 'Man',
    design: 'perfectly imperfect',
    type: 'teeshirts',
    price: 25,
  },
  {
    id: 26,
    title: 'Perfectly Imperfect Oversized Woman Teeshirt',
    img_path: 'perfectly imperfect/perfectly imperfect oversized woman tee',
    genre: 'Woman',
    design: 'perfectly imperfect',
    type: 'teeshirts',
    price: 25,
  },
  {
    id: 27,
    title: 'Techno Music Just Saved My Life Man Teeshirt',
    img_path: 'techno music just saved my life/techno music just saved my life man tee',
    genre: 'Man',
    design: 'techno music just saved my life',
    type: 'teeshirts',
    price: 25,
  },
  {
    id: 28,
    title: 'Techno Music Just Saved My Life Woman Teeshirt',
    img_path: 'techno music just saved my life/techno music just saved my life woman tee',
    genre: 'Woman',
    design: 'techno music just saved my life',
    type: 'teeshirts',
    price: 25,
  },
  {
    id: 29,
    title: 'Techno Music Just Saved My Life Oversized Man Teeshirt',
    img_path: 'techno music just saved my life/techno music just saved my life oversized man tee',
    genre: 'Man',
    design: 'techno music just saved my life',
    type: 'teeshirts',
    price: 25,
  },
  {
    id: 30,
    title: 'Techno Music Just Saved My Life Oversized Woman Teeshirt',
    img_path: 'techno music just saved my life/techno music just saved my life oversized woman tee',
    genre: 'Woman',
    design: 'techno music just saved my life',
    type: 'teeshirts',
    price: 25,
  },

  {
    id: 31,
    title: 'Connection Man Hoodie',
    img_path: 'connection/connection man hoodie',
    genre: 'Man',
    design: 'connection',
    type: 'hoodies',
    price: 50,
  },
  {
    id: 32,
    title: 'Connection Woman Hoodie',
    img_path: 'connection/connection woman hoodie',
    genre: 'Woman',
    design: 'connection',
    type: 'hoodies',
    price: 50,
  },
  {
    id: 33,
    title: 'Dont Panic Its Legal Man Hoodie',
    img_path: 'don_t panic it_s legal/don_t panic it_s legal man hoodie',
    genre: 'Man',
    design: 'don_t panic it_s legal',
    type: 'hoodies',
    price: 50,
  },
  {
    id: 34,
    title: 'Dont Panic Its Legal Woman Hoodie',
    img_path: 'don_t panic it_s legal/don_t panic it_s legal woman hoodie',
    genre: 'Woman',
    design: 'don_t panic it_s legal',
    type: 'hoodies',
    price: 50,
  },
  {
    id: 35,
    title: 'Mushroom Head Man Hoodie',
    img_path: 'mushroom head/mushroom head man hoodie',
    genre: 'Man',
    design: 'mushroom head',
    type: 'hoodies',
    price: 50,
  },
  {
    id: 36,
    title: 'Mushroom Head Woman Hoodie',
    img_path: 'mushroom head/mushroom head woman hoodie',
    genre: 'Woman',
    design: 'mushroom head',
    type: 'hoodies',
    price: 50,
  },
  {
    id: 37,
    title: 'Music and Peace Man Hoodie',
    img_path: 'music and peace/music and peace man hoodie',
    genre: 'Man',
    design: 'music and peace',
    type: 'hoodies',
    price: 50,
  },
  {
    id: 38,
    title: 'Music and Peace Woman Hoodie',
    img_path: 'music and peace/music and peace woman hoodie',
    genre: 'Woman',
    design: 'music and peace',
    type: 'hoodies',
    price: 50,
  },
  {
    id: 39,
    title: 'Perfectly Imperfect Man Hoodie',
    img_path: 'perfectly imperfect/perfectly imperfect man hoodie',
    genre: 'Man',
    design: 'perfectly imperfect',
    type: 'hoodies',
    price: 50,
  },
  {
    id: 40,
    title: 'Perfectly Imperfect Woman Hoodie',
    img_path: 'perfectly imperfect/perfectly imperfect woman hoodie',
    genre: 'Woman',
    design: 'perfectly imperfect',
    type: 'hoodies',
    price: 50,
  },
  {
    id: 41,
    title: 'Techno Music Just Saved my Life Man Hoodie',
    img_path: 'techno music just saved my life/techno music just saved my life man hoodie',
    genre: 'Man',
    design: 'techno music just saved my life',
    type: 'hoodies',
    price: 50,
  },
  {
    id: 42,
    title: 'Techno Music Just Saved my Life Woman Hoodie',
    img_path: 'techno music just saved my life/techno music just saved my life woman hoodie',
    genre: 'Woman',
    design: 'techno music just saved my life',
    type: 'hoodies',
    price: 50,
  },

  {
    id: 43,
    title: 'Partee Bag',
    img_path: 'partee bag/partee bag',
    genre: 'Unisex',
    design: 'skull',
    type: 'accessories',
    name: 'bag',
    price: 25,
  },
  {
    id: 44,
    title: 'Partee Fan',
    img_path: 'partee fan/partee fan',
    genre: 'Unisex',
    design: 'abstract',
    type: 'accessories',
    name: 'fan',
    price: 15,
  },
]
